import json
import sys

# Define our enforceable engineering bounds (in nanoseconds)
CONTRACTS = {
    "BM_Parser_AddOrder": {"p99": 120.0},
    "BM_OrderBook_Add": {"p99": 140.0},
    "BM_Match_SingleLevel": {"p99": 200.0},
    "BM_Match_MultiLevelSweep": {"p99": 250.0}
}

def validate_benchmark(json_path):
    with open(json_path, 'r') as f:
        data = json.load(f)

    failed = False
    
    print("Evaluating Performance Contracts...")
    print("-" * 50)
    
    for bench in data.get("benchmarks", []):
        name = bench["name"]
        
        # We are looking for the _p99 aggregated stats generated by google benchmark
        # if --benchmark_repetitions is used. For a simple run without repetitions,
        # we check the cpu_time directly as a proxy for the single run.
        # But let's assume we check 'real_time' or 'cpu_time' for the raw benchmark name if it matches.
        
        base_name = name.split('_mean')[0].split('_median')[0].split('_stddev')[0].split('_p99')[0]
        
        if base_name in CONTRACTS:
            contract = CONTRACTS[base_name]
            p99_limit = contract["p99"]
            
            # If repetitions are run, look for the p99 row
            if name.endswith("_p99"):
                actual = bench["real_time"]
                status = "PASS" if actual < p99_limit else "FAIL"
                print(f"[{status}] {base_name} P99: {actual:.2f} ns (Contract: < {p99_limit} ns)")
                if actual >= p99_limit:
                    failed = True
            
            # If no repetitions are run, just use the raw real_time as a crude check
            elif not name.endswith("_mean") and not name.endswith("_median") and not name.endswith("_stddev"):
                # We'll only enforce the crude check if there isn't a p99 explicitly
                # To be safe, we check if repetitions was 1
                if data["context"].get("repetitions", 1) == 1:
                    actual = bench["real_time"]
                    status = "PASS" if actual < p99_limit else "FAIL"
                    print(f"[{status}] {base_name} Raw: {actual:.2f} ns (Contract: < {p99_limit} ns)")
                    if actual >= p99_limit:
                        failed = True

    print("-" * 50)
    
    if failed:
        print("ERROR: One or more performance contracts were violated!")
        sys.exit(1)
    else:
        print("SUCCESS: All performance contracts satisfied.")
        sys.exit(0)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python validate_contracts.py <benchmark_result.json>")
        sys.exit(1)
    validate_benchmark(sys.argv[1])
